### ISSUE TITLE
only cpu

### ISSUE THREAD

**Issue by rajkumarTechy** [computervisioneng/automatic-number-plate-recognition-python-yolov8#11]
![Screenshot (14)](https://github.com/computervisioneng/automatic-number-plate-recognition-python-yolov8/assets/70502152/9610dbc0-3677-4723-bc64-192b99d023a9)

**Comment by fitratgulmamadov** [comment]
Is it possible run it on GPU?

**Comment by rajkumarTechy** [comment]
> Is it possible run it on GPU?

Yes you can ..
