### ISSUE TITLE
ModuleNotFoundError: No module named 'sort'

### ISSUE THREAD

**Issue by lordwildbeast** [computervisioneng/automatic-number-plate-recognition-python-yolov8#2]
i have install all requirements from requirements.txt and i have this error message when running main.py

**Comment by sawlachintan** [comment]
In the video, he says that we need to download the "sort" repository from [Abewley Sort](https://github.com/abewley/sort). Video URL - https://youtu.be/fyJB1t0o0ms?t=1120
